#pragma once

#define NUM_PINS 8

#define MAX_POS 2300
#define DEAD_ZONE 1500
#define MIN_POS 1400

#define NO_THROTTLE_INTERVAL 500
#define FULL_THROTTLE_INTERVAL 10

#define SAMPLES 10
#define REFRESH_THROTTLE 10
#define CONTROL_PIN 36

#define STATE_ON LOW
#define STATE_OFF HIGH